sources:
  - name: clober-v1
    handler:
      graphql:
        endpoint: '{context.url:https://subgraph.satsuma-prod.com/f6a8c4889b7b/clober/core-v1-subgraph/api}'

documents:
  - ./apis/**/*.graphql
  - ./__tests__/**/*.graphql


codegen:
  contextType: 'MeshContext & { url: string }'
