sources:
  - name: clober-v1
    handler:
      graphql:
        endpoint: '{context.url:https://api.studio.thegraph.com/query/49804/core-v1-arbitrum-subgraph/version/latest}'

documents:
  - ./apis/**/*.graphql
  - ./__tests__/**/*.graphql


codegen:
  contextType: 'MeshContext & { url: string }'
